In [2]:
import pandas as pd
import numpy as np
import seaborn as sbn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
datos = pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.csv")
datos.head(10)

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   
5    Male  29.0    1.62    53.0                             no  yes   2.0   
6  Female  23.0    1.50    55.0                            yes  yes   3.0   
7    Male  22.0    1.64    53.0                             no   no   2.0   
8    Male  24.0    1.78    64.0                            yes  yes   3.0   
9    Male  22.0    1.72    68.0                            yes  yes   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   
5  3.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   
6  3.0  Sometimes    no   2.0   no  1.0  0.0   Sometimes   
7  3.0  Sometimes    no   2.0   no  3.0  0.0   Sometimes   
8  3.0  Sometimes    no   2.0   no  1.0  1.0  Frequently   
9  3.0  Sometimes    no   2.0   no  1.0  1.0          no   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II  
5             Automobile        Normal_Weight  
6              Motorbike        Normal_Weight  
7  Public_Transportation        Normal_Weight  
8  Public_Transportation        Normal_Weight  
9  Public_Transportation        Normal_Weight

In [3]:
datos.describe()
datos['MTRANS'].unique()


array(['Public_Transportation', 'Walking', 'Automobile', 'Motorbike',
       'Bike'], dtype=object)

In [4]:
rng = np.random.RandomState(seed=42)
datos["random_cat"] = rng.randint(3, size=datos.shape[0])
datos["random_num"] = rng.randn(datos.shape[0])
categorical_columns = ["Gender", "family_history_with_overweight", "FAVC", "CAEC","SMOKE", "SCC","CALC","MTRANS","random_cat"]
numerical_columns = ["Age", "FCVC", "NCP", "CH2O", "FAF","TUE","random_num"]
X = datos[categorical_columns + numerical_columns]
y = datos["NObeyesdad"]
y = datos['NObeyesdad'].map({'Normal_Weight': 0, 'Insufficient_Weight': 1, 'Obesity_Type_I':2,'Obesity_Type_II':3, 'Obesity_Type_III':4, 'Overweight_Level_I':5,'Overweight_Level_II':6})
yname = ["NObeyesdad"]
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

In [5]:
X_train.head(10)

Gender family_history_with_overweight FAVC        CAEC SMOKE SCC  \
1007    Male                            yes  yes   Sometimes    no  no   
822   Female                            yes  yes   Sometimes    no  no   
372   Female                             no  yes   Sometimes    no  no   
836   Female                            yes  yes   Sometimes    no  no   
811     Male                            yes  yes   Sometimes    no  no   
1216  Female                            yes  yes   Sometimes    no  no   
1751    Male                            yes  yes   Sometimes    no  no   
2       Male                            yes   no   Sometimes    no  no   
295   Female                             no   no   Sometimes    no  no   
610   Female                            yes  yes  Frequently    no  no   

            CALC                 MTRANS  random_cat        Age      FCVC  \
1007   Sometimes  Public_Transportation           1  22.943130  1.882235   
822    Sometimes  Public_Transportation           1  21.938831  1.906194   
372           no             Automobile           2  18.000000  3.000000   
836    Sometimes             Automobile           2  31.255587  2.615788   
811    Sometimes  Public_Transportation           1  19.741202  2.000000   
1216          no             Automobile           1  42.316070  2.490507   
1751   Sometimes  Public_Transportation           0  26.199321  2.423291   
2     Frequently  Public_Transportation           2  23.000000  2.000000   
295           no                Walking           1  16.000000  2.000000   
610           no  Public_Transportation           2  21.798856  2.979383   

           NCP      CH2O       FAF       TUE  random_num  
1007  1.240046  2.000000  0.000000  1.541493   -0.147780  
822   3.987707  2.597746  1.922234  1.376124    1.173125  
372   3.000000  1.000000  0.000000  2.000000    0.240753  
836   3.000000  1.771781  0.759422  0.686529   -0.787784  
811   3.000000  2.177386  0.336814  0.004813    0.006422  
1216  2.974204  1.846754  0.000000  0.000000    0.418398  
1751  3.000000  2.902682  1.243567  0.555591   -0.924466  
2     3.000000  2.000000  2.000000  1.000000   -0.321635  
295   1.000000  1.000000  0.000000  1.000000   -0.209324  
610   3.000000  2.975887  0.945093  1.241755    0.586694

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn import linear_model, tree
from sklearn.feature_selection import RFE
from sklearn import linear_model, tree
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeClassifier
from dtreeviz.trees import dtreeviz
from sklearn.model_selection import GridSearchCV
import joblib as joblib
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization, Activation
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, KFold
import keras.backend as K
from scikeras.wrappers import KerasClassifier

categorical_encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value", unknown_value=-1, encoded_missing_value=-1
)
numerical_pipe = StandardScaler()

preprocessing = ColumnTransformer(
    [
        ("Codificación de Categóricas", categorical_encoder, categorical_columns),
        ("Transformación de numéricas", numerical_pipe, numerical_columns),
    ],
    verbose_feature_names_out=False,
)

modelo_logistico= LogisticRegression()
gnb=GaussianNB()
arbol=DecisionTreeClassifier(criterion='gini', min_samples_split=100, min_samples_leaf=50)
random_forest = RandomForestClassifier(random_state=42)
neural_netwrok=Sequential()
neural_netwrok.add(Dense(units=1, input_shape=(16,), activation='sigmoid'))
neural_netwrok.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

modelos=[modelo_logistico,gnb,arbol,random_forest, neural_netwrok]
resultados=[]
for modelo in modelos:
    nombre_modelo=f'{modelo}.joblib'
    flujo = Pipeline(
        [
            ("Preprocesamiento", preprocessing),
            ("Clasificador", modelo),
        ]
    )
    flujo.fit(X_train, y_train)
    joblib.dump(flujo, nombre_modelo)
    salida=joblib.dump(flujo, nombre_modelo)
    resultados.append(salida)

from sklearn.metrics import classification_report
#print(classification_report(y_test, y_pred))


c:\Users\CARLOS MARIO\Anaconda3\envs\tensor_310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\CARLOS MARIO\Anaconda3\envs\tensor_310\lib\site-packages\tensorflow\python\util\dispatch.py:1260: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)




50/50 [==============================] - 4s 11ms/step - loss: 0.0000e+00 - accuracy: 0.1295


OSError: [Errno 22] Invalid argument: '<keras.src.engine.sequential.Sequential object at 0x000001B7DB56D000>.joblib'

In [12]:
resultados

[['LogisticRegression().joblib'],
 ['GaussianNB().joblib'],
 ['DecisionTreeClassifier(min_samples_leaf=50, min_samples_split=100).joblib'],
 ['RandomForestClassifier(random_state=42).joblib']]

In [33]:

rf=joblib.load('r_RandomForestClassifier(random_state=42).joblib')
confusion_matrix(y_test, rf.predict(X_test))




array([[58,  4,  2,  1,  0,  2,  5],
       [ 9, 55,  0,  0,  0,  4,  0],
       [ 4,  0, 74,  4,  0,  3,  3],
       [ 1,  0,  1, 69,  0,  0,  3],
       [ 1,  0,  0,  0, 80,  0,  0],
       [ 9,  1, 10,  0,  1, 51,  1],
       [ 8,  1,  5,  3,  0,  2, 53]], dtype=int64)

In [34]:
log=joblib.load('r_LogisticRegression().joblib')
confusion_matrix(y_test, log.predict(X_test))

array([[26, 19,  4,  5,  1, 12,  5],
       [14, 39,  6,  4,  0,  4,  1],
       [ 2,  4, 62, 13,  0,  4,  3],
       [ 1,  1,  8, 58,  0,  1,  5],
       [ 0,  1,  0,  0, 80,  0,  0],
       [ 6,  4, 14, 10,  4, 30,  5],
       [ 6,  5, 25, 17,  2,  5, 12]], dtype=int64)

In [12]:
nb=joblib.load('r_GaussianNB().joblib')
confusion_matrix(y_test, nb.predict(X_test))

array([[14, 30,  8,  7,  0,  9,  4],
       [ 3, 45,  2, 16,  0,  2,  0],
       [ 0,  3, 43, 40,  0,  0,  2],
       [ 3,  1,  0, 68,  0,  0,  2],
       [ 0,  1,  0,  0, 80,  0,  0],
       [ 7,  4, 24, 18,  0, 19,  1],
       [ 3,  6, 12, 37,  0,  1, 13]], dtype=int64)

In [36]:
log.fit(X_train,y_train)

c:\Users\CARLOS MARIO\Anaconda3\envs\tensor_310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Pipeline(steps=[('Preprocesamiento',
                 ColumnTransformer(transformers=[('Codificación de Categóricas',
                                                  OrdinalEncoder(encoded_missing_value=-1,
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['Gender',
                                                   'family_history_with_overweight',
                                                   'FAVC', 'CAEC', 'SMOKE',
                                                   'SCC', 'CALC', 'MTRANS',
                                                   'random_cat']),
                                                 ('Transformación de numéricas',
                                                  StandardScaler(),
                                                  ['Age', 'FCVC', 'NCP', 'CH2O',
                                                   'FAF', 'TUE',
                                                   'random_num'])],
                                   verbose_feature_names_out=False)),
                ('Clasificador', LogisticRegression())])